version: '3.6'
services:
  mysql:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-gan-test
  
    environment:
     - MYSQL_HOST=127.0.0.1
     - MYSQL_PORT=3306
     - MYSQL_DATABASE=gan
     - MYSQL_USER=user
     - MYSQL_PASSWORD=pass
     - MYSQL_RANDOM_ROOT_PASSWORD=yes
 
    ports:
      - 3306:3306

